package events

type EventType = uint16
type Event interface {
	Type() EventType
}

const (
	START_TRANSACTION_EVENT EventType = iota
	COMMIT_TRANSACTION_EVENT
	CREATE_TABLE_EVENT
	UPDATE_TABLE_EVENT
	DROP_TABLE_EVENT
	INSERT_ENTRY_EVENT
	UPDATE_ENTRY_EVENT
	DELETE_ENTRY_EVENT
	UPDATE_DB_VERSION_EVENT
	FREE_PAGES_EVENT
)
